# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    xarm_1s_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

xarm_1s_arm_controller:
  ros__parameters:
    joints:
      - arm6
      - arm5
      - arm4
      - arm3
      - arm2
    command_interfaces:
      - position
    state_interfaces:
      - position
hand_controller:
  ros__parameters:
    joint: arm1